function createfigure(X1, Y1, XMatrix1, YMatrix1, X2, Y2)
%CREATEFIGURE(X1, Y1, XMatrix1, YMatrix1, X2, Y2)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  XMATRIX1:  matrix of plot x data
%  YMATRIX1:  matrix of plot y data
%  X2:  vector of plot x data
%  Y2:  vector of plot y data

%  Auto-generated by MATLAB on 02-Jul-2022 14:34:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot1 = plot(X1,Y1,'Marker','.','LineStyle','none');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1,3266,2890);
% Create datatip
datatip(plot1,'DataIndex',309);

% Create multiple line objects using matrix input to plot
plot(XMatrix1,YMatrix1,'LineWidth',2,'Color',[1 0 0],'Parent',axes1);

% Create plot
plot(X2,Y2,'MarkerFaceColor',[1 1 0],'MarkerSize',3,'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',...
    [1901.84049079755 1500 1]);
